
name: Grilo SC Analysis for Interpreted Languages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  sonar-analysis:
    name: SonarCloud Analysis for Interpreted Languages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >-
            -Dsonar.projectKey=grilo-org_20251030T211735_Viniciusrbr_fincheck
            -Dsonar.projectName=20251030T211735_Viniciusrbr_fincheck
            -Dsonar.organization=grilo-org
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**,vendor/**,**/*.test.*,**/*.spec.*,**/*.min.js,**/*.min.css,venv/**,__pycache__/**,*.pyc

